### ISSUE TITLE
Formatting Error in Overrides File Location

### ISSUE THREAD

**Issue by MetalNeo** [dr460nf1r3/firedragon-browser#10]
There is an extra `/` in the file path for the Overrides file at the bottom of `firedragon.cfg`. This is causing the path to include the literal string `profile_directory` instead of inserting the user's home directory path.

See: https://gitlab.com/librewolf-community/settings/-/blob/master/librewolf.cfg

**Comment by dr460nf1r3** [comment]
Well spotted! Thanks for reporting, its fixed in the last commit :)
