### ISSUE TITLE
Consider migrating to Codeberg

### ISSUE THREAD

**Issue by ThousandDemonDaggers** [dr460nf1r3/firedragon-browser#100]
Moving everything to [Codeberg](https://codeberg.org) would be great, as it is a libre, free, open-source, privacy-friendly and non-profit git platform from Germany, running the Gittea soft-fork [Forgejo](https://forgejo.org).
Instead, GitHub is closed source software owned by Microsoft, opposing to Firedragon.

* https://codeberg.org/Recommendations/Mirror_to_Codeberg
* https://nogithub.codeberg.page

**Comment by Technetium1** [comment]
This repo is only a mirror, the true home is not GitHub.
https://gitlab.com/garuda-linux/firedragon

**Comment by dr460nf1r3** [comment]
While Codeberg and their CI make a quite nice impression (have been working with Forgejo before), I'm personally not interested in maintaining another public space for now, even if it's a mirror. Might reconsider this in the future.
