### ISSUE TITLE
[BUG] Issues when Accessing Twitch.tv

### ISSUE THREAD

**Issue by alkaris2** [dr460nf1r3/firedragon-browser#101]
The browser has some serious issues when being "Detected" for Compatible Browsers when trying to login to Twitch.tv.

> "Your browser is currently not supported."

The "official" browsers Twitch supports are Edge, Safari, Google Chrome and Firefox, the problem lies in detecting the browsers compatibility. If anything some feature needs to be implemented to circumvent being detected as "not compatible browser" to disable these checks, or at the very lest bypass this check.

Twitch uses some XSS Detection method and it sets the mode to blocked so it ends up stopping you from trying to login, even if you've cleared all site data and cookies, this is stopping you from logging back in to your account.

The only workaround fix is to copy the `cookies.sqlite` file from your Firefox user profile after logging in to your account and then import that file into FireDragon to login. Essentially you have to steal your own cookies from another browser JUST to login. I've had this issue happen on other sites like SoundCloud, because they have same kind of XSS detection things going on and sends `mode=blocked` in the XSS Requests, because even if you input correct login details you will still be blocked from logging in entirely. The functionality of the Internet is broken when they use broken methods to detect things, and so we have to circumvent their detection methods just to login.

I'm labeling this as critical issue in the functionality of the Internet and web browsers. Because there's no legitimate way to tell or verify compatible browsers, because most of the time it's guess work.

https://help.twitch.tv/s/article/supported-browsers?language=en_US

**Comment by dr460nf1r3** [comment]
Thanks for searching issues before posting. 

https://github.com/dr460nf1r3/firedragon-browser/issues/49#issuecomment-2294745486
