### ISSUE TITLE
Implementing features from Zen Browser

### ISSUE THREAD

**Issue by ThousandDemonDaggers** [dr460nf1r3/firedragon-browser#103]
[Zen Browser](https://www.zen-browser.app/) is the new kid in town but is already rich of [features](https://github.com/zen-browser/desktop). Wouldn't it be appropriate to consider integrating Zen features into Firedragon?

**Comment by dr460nf1r3** [comment]
This topic has been brought up before, and right now I think it doesn't make that much sense. Zen looks pretty, but is still in alpha. I'm also quite sure that both Floorp and Zen codes might clash and cause issues given they both tackle similar things.
