### ISSUE TITLE
[Bug] 11.17.4-3 Youtube videos do not load

### ISSUE THREAD

**Issue by Coolcoder360** [dr460nf1r3/firedragon-browser#106]
updated to 11.17.4-3 and Youtube videos fail to load.
Checked on firefox v129.0.2 and the youtube videos work as expected.

I tested with Firedragon with ublock origin disabled and enabled, same result, firefox works with ublock origin enabled.

In the console I saw some different logs in firedragon than I did in firefox, in firedragon I saw CORS failures for a googlevideo.com, which were not in the firefox logs.
Otherwise there were other CORS failures that were shared between both.

**Comment by stefanwimmer128** [comment]
Probably the same issue as [here](https://forum.garudalinux.org/t/firedragon-media-playback-messed-up-11-17-4-2-1/38764/1). In that case it will be fixed in the newly released version 11.17.6-1.

**Comment by Coolcoder360** [comment]
Thanks!
I totally searched in github for youtube issues but missed checking the forum...

**Comment by Coolcoder360** [comment]
Yeah I tested on 11.17.6-1 and it seems this is resolved.
