### ISSUE TITLE
Extensions unable to detect the correct version

### ISSUE THREAD

**Issue by choc1024** [dr460nf1r3/firedragon-browser#107]
OS: Garuda Linux KDE dr460nf1r3 Gaming edition
FireDragon Version: 11.17.6-1 (64-bit)

So I install ed the Cookie AutoDelete extension and it seems that it can't detect the version of FireDragon. My firedragon version is 11.17.6-1 based on firefox 120+, but extensions can't detect that, they only see the "11" part of the 11.17.6-1, and so they think that I am using an outdated version and many features are disabled.

**Comment by dr460nf1r3** [comment]
https://firedragon.garudalinux.org/workarounds#add-ons-not-updating-both-auto-and-manual

**Comment by choc1024** [comment]
But can't we change the version to be something similar to the firefox version, or at least provide the current firefox version to extensions?

I also tried changing distribution.iniFile.exists.appversion, extensions.lastAppVersion and floorp.startup.oldVersion to 128.2.0, but apparently FireDragon just resets them.

**Comment by stefanwimmer128** [comment]
FireDragon v11.17.7-2 should now expose the correct underlying Firefox version.

**Comment by dr460nf1r3** [comment]
@FGD-Garuda just reported it working, awesome :)
