### ISSUE TITLE
Your browser is managed by your organization

### ISSUE THREAD

**Issue by choc1024** [dr460nf1r3/firedragon-browser#108]
How do I get rid of this?
Garuda Linux KDE Dragonized Gaming edition, FireDragon 11.17.6-1

**Comment by dr460nf1r3** [comment]
Can be done by deleting policies.json. This is however used to apply some of our settings, so it's working as intended.

**Comment by stefanwimmer128** [comment]
I could add [this patch](https://codeberg.org/librewolf/source/src/branch/main/patches/ui-patches/remove-organization-policy-banner.patch) to just remove the warning from the UI?

**Comment by dr460nf1r3** [comment]
Sounds good, I think this unnecessarily scares people for no reason 👀

**Comment by stefanwimmer128** [comment]
Banner will be removed in v11.17.7-2.

**Comment by choc1024** [comment]
But that isn't the main problem, because this policy thing is not allowing me to update. It sets "DisableAppUpdate" to true, and so I am unable to update, please help. I also can't find the policies.json.

**Comment by dr460nf1r3** [comment]
This is about system updates, which Linux always sets to false. We have a package manager to do this for us. Are you talking about extensions?

**Comment by choc1024** [comment]
I just found the policies.json and changed DisableAppUpdate to false, restarted FireDragon. I am talking about Updating FireDragon. I already tried "yay", it updated packages but did not update FireDragon. I clicked the hamburger menu > Help > About FireDragon. That didn't update either. Both "garuda-update" and "pacman -Syu" returned "there is nothing to do".

**Comment by choc1024** [comment]
So now... how do I update?

**Comment by stefanwimmer128** [comment]
What version does it show under Help > About FireDragon?

**Comment by choc1024** [comment]
anyone?

**Comment by stefanwimmer128** [comment]
As far as I can see the problem is the package in the Garuda repository is out of date. That's why a system update did not update FireDragon. Once the package is updated in the repository you can update FireDragen through system updates like normal.

**Comment by choc1024** [comment]
so, basically, I just need to wait for the package to be updated in the repository?

**Comment by stefanwimmer128** [comment]
yes

**Comment by choc1024** [comment]
but look:
https://aur.archlinux.org/packages/firedragon
https://aur.archlinux.org/packages/firedragon-bin

those are both at the latest version. Maybe the preinstalled firedragon is from a different repo

**Comment by choc1024** [comment]
I think garuda's servers are down

**Comment by stefanwimmer128** [comment]
Yes, the AUR packages are up to date, but the Garuda repository is separate from that and is still at 1.17.6-1.1:
![image](https://github.com/user-attachments/assets/fb27ddb7-3fc4-4378-b4fc-3ec65c155693)

**Comment by choc1024** [comment]
Garuda's Whoogle seems to be down, but the rest of the servers seem to be fine. BTW, which command is that? I come from Kubuntu, just started using garuda a few weeks ago

**Comment by stefanwimmer128** [comment]
```
pacman -Si firedragon
```

**Comment by choc1024** [comment]
yeah... still not updated. I guess I'll remove the FireDragon from the garuda repository and replace it with the chaotic-aur

**Comment by choc1024** [comment]
OK, did `sudo pacman -Rns firedragon firedragon-extension-plasma-integration`, then `rm -rf ~/.
firedragon/`, `sudo pacman -S chaotic-aur/firedragon chaotic-aur/firedragon-extension-plasma-integration`. Now it seems to be fine.

![Screenshot_20240827_141354](https://github.com/user-attachments/assets/dd9abd39-d311-4f7b-a51a-72a5f63afea1)

**Comment by dr460nf1r3** [comment]
The deploying pipeline must've failed, I'll look into this soon.

**Comment by choc1024** [comment]
OK, thanks. BTW, just updated to 1.17.8
