### ISSUE TITLE
Heavy CPU utilization on YouTube Videos

### ISSUE THREAD

**Issue by Exanime4Ever** [dr460nf1r3/firedragon-browser#111]
I have been using FireDragon for about a year now and love it. Since the last upgrade to 11.17.8-1 which I installed yesterday, I have noticed degradation (stutter, skipping, pausing)  on YouTube videos. I think it's all videos as I also noticed it on F1TV but a lot less.

The degradation seems to be related to heavy CPU utilization, the core assigned seems to be regularly maxed out and overall using over 80%. In contrasts, Firefox uses 25% or so playing the same videos.

My system is not the beefiest but definitely able to play vids without a blip. Hardware acceleration is on.

![image](https://github.com/user-attachments/assets/4caaa96d-a2a2-44d3-9819-79155c087b35)

**Comment by Technetium1** [comment]
`about:config`
```
layers.acceleration.force-enabled
```
set true. Does it help?
Does this happen in a new profile? https://firedragon.garudalinux.org/troubleshooting

**Comment by Exanime4Ever** [comment]
Thanks for the reply. I set layers.acceleration.force-enabled to true (was false), will take it for a spin and report back

If that fails I will try the new profile idea as well

**Comment by Exanime4Ever** [comment]
Changes did not fix the issue. 156% CPU utilization for a simple 720p vid

**Comment by Exanime4Ever** [comment]
I continued using FireDragon figuring it would work OK as long as I was not watching videos but I can see the same spikes in CPU coming from the firedragon process even when not playing any media.

![image](https://github.com/user-attachments/assets/6bda0246-3008-473d-9f5b-ec4bd77fa4da)

**Comment by Technetium1** [comment]
Assuming you have already tried a new profile at this point? Open `about:support` then choose `Copy text to clipboard` and post it here in a single comment. Click `Preview` and scroll through it in case you want to censor something.

- I don't use Wayland, so I really can't be sure, but maybe you could set `MOZ_ENABLE_WAYLAND=1` per https://wiki.archlinux.org/title/Firefox#Wayland
- Are you sure your hardware acceleration is working properly? https://wiki.archlinux.org/title/Hardware_video_acceleration#Verification
- Does `radeontop` show activity when videos are playing?
- The reason I ask for `about:support` is to check for a logged decoding failure: https://wiki.archlinux.org/title/Firefox#Hardware_video_acceleration
  - There is another step in the previous link to try with `MOZ_LOG="FFmpegVideo:5"`
