### ISSUE TITLE
"When you open a link, image or media in a new tab, switch to it immediately" is ignored. 

### ISSUE THREAD

**Issue by Exanime4Ever** [dr460nf1r3/firedragon-browser#112]
No matter whether this setting is checked on or off, links open in new tabs but browser does not focus on them.

The only "workaround" is to control+click on a link, this does open the link on a new tab and focus on it immediately

**Comment by dr460nf1r3** [comment]
Hey :) 
To confirm - you enabled the setting and made use of it like right-clicking on a link, open in new tab? Can't replicate this locally with this procedure.

**Comment by Exanime4Ever** [comment]
Right-click + Open link in a new tab, does seem to work. 

However, any link that automatically opens in a new tab, does open but focus does not shift to the new tab. Be it from another page in FireDragon or another application (like email client, signal desktop client or Teams)

**Comment by Exanime4Ever** [comment]
These change seems to solve the problem (still testing)

     browser.tabs.loadDivertedInBackground => when you divert a script-generated new window to a new tab using Ctrl+click, or when a page uses the target attribute to launch a link in a new window and you divert it to a new tab
        default = false, make the new tab active 


Switched it to "false" (was true)

from this article: https://support.mozilla.org/en-US/questions/1066419

**Comment by dr460nf1r3** [comment]
That's good news! Need to test it too, if it works we might include it as default.

**Comment by Exanime4Ever** [comment]
Seems reasonable. Thanks for your hard work
