### ISSUE TITLE
Youtube videos starting up paused

### ISSUE THREAD

**Issue by Elysium1436** [dr460nf1r3/firedragon-browser#12]
I'm on garuda linux with the qtile version. Instead of youtube videos starting when I click on them, they start paused and not loaded.
![image](https://user-images.githubusercontent.com/61297992/153086727-ab039cd4-7d20-4271-a009-05e8c61a578e.png)

**Comment by dr460nf1r3** [comment]
Check the icon left to the address bar, clicking it should bring up a drop-down where autoplay can be enabled 👀
