### ISSUE TITLE
Cant Download Anything 

### ISSUE THREAD

**Issue by nakrosrex** [dr460nf1r3/firedragon-browser#120]
Hey i am using firedragon 11.20.0-1 on latest archlinux i downloaded with aur and the problem is this i cant download anything using latest firedragon  browser the issue is been since this updates previous version were fine i uploaded a sample video of it whats the actual problem is and even cant open file manager for uploading files to anywhere like this video i uploaded by drag and drop but it is not always practical solution like to import bookmarks or export  

https://github.com/user-attachments/assets/d3f78fe7-1b91-400d-bd9f-ff1d62bdd364

**Comment by FGD-Garuda** [comment]
Hello, that's very annoying indeed!

At the moment I am unable to reproduce the issue:
![image](https://github.com/user-attachments/assets/a202868c-81c4-4ce0-bd32-69016eb1d10d)

Are you using `firedragon` package built on your machine through Aur or are you using `firedragon-bin`?

**Comment by stefanwimmer128** [comment]
What desktop are you using? If it's wlroots-based look [here](https://github.com/dr460nf1r3/firedragon-browser/issues/98#issuecomment-2363810846).

**Comment by nakrosrex** [comment]
> Hello, that's very annoying indeed!
> 
> At the moment I am unable to reproduce the issue: ![image](https://private-user-images.githubusercontent.com/35015576/382474590-a202868c-81c4-4ce0-bd32-69016eb1d10d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MDg1NjUsIm5iZiI6MTczMDYwODI2NSwicGF0aCI6Ii8zNTAxNTU3Ni8zODI0NzQ1OTAtYTIwMjg2OGMtODFjNC00Y2UwLWJkMzItNjkwMTZlYjFkMTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDA0MzEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhY2VkZTc0NGRlOGJjNGM1Yjc3ZWE0YTBhNGEyZDYwMDk2NmIwOGM1ODNlODIxZjE3OGU5NjEwNmZkMWIyMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lFt6G_jwo7BeX8AwEQ0p6Am_DOZwY9RWu3zQ8Lu-BX4)
> 
> Are you using `firedragon` package built on your machine through Aur or are you using `firedragon-bin`?

I am using firedragon-bin i got the solution it that when you uncheck the 'Always ask you where to save files' (attach the picture)in settings>files and application than i can download 
![solution](https://github.com/user-attachments/assets/d9c6403f-4a1b-4615-b3b2-24cd36e473b7)

**Comment by nakrosrex** [comment]
> What desktop are you using? If it's wlroots-based (not KDE or GNOME) look [here](https://github.com/dr460nf1r3/firedragon-browser/issues/98#issuecomment-2363810846).

Hey i am using xfce4 x11 and archlinux  , and i got the solution [posted above]

**Comment by stefanwimmer128** [comment]
> xfce4 x11

Ok, FireDragon uses XDG Desktop Portal for the File Chooser, so if you need to be able to select the download location or get other problems with file dialogs, setting up `xdg-desktop-portal-gtk` should work:

Install `xdg-desktop-portal-gtk` and modify `~/.config/xdg-desktop-portal/portals.conf`:

```
[preferred]
org.freedesktop.impl.portal.FileChooser=gtk
```

**Comment by nakrosrex** [comment]
> > xfce4 x11
> 
> Ok, FireDragon uses XDG Desktop Portal for the File Chooser, so if you need to be able to select the download location or get other problems with file dialogs, setting up `xdg-desktop-portal-gtk` should work:
> 
> Install `xdg-desktop-portal-gtk` and modify `~/.config/xdg-desktop-portal/portals.conf`:
> 
> ```
> [preferred]
> org.freedesktop.impl.portal.FileChooser=gtk
> ```

Thanks this solution worked

**Comment by dr460nf1r3** [comment]
Would be a good idea to add this to the known issues section of the docs. Thanks for reporting back :)
