### ISSUE TITLE
Global App Menu breaks after enabling Wayland

### ISSUE THREAD

**Issue by nathandaven** [dr460nf1r3/firedragon-browser#13]
After using `MOZ_ENABLE_WAYLAND=1` in `/etc/enviroment` to enable Wayland in Firedragon, the global menu in KDE disappears, any fix for this? Thanks in advance!

**Comment by dr460nf1r3** [comment]
Hey there! This was reported at [Gitlab](https://gitlab.com/dr460nf1r3/settings/-/issues/14) already, I'm assuming it's a limitation of the appmenu patch - I can't fix that sadly.
