### ISSUE TITLE
Browser lag while using the microphone

### ISSUE THREAD

**Issue by UltraBlackLinux** [dr460nf1r3/firedragon-browser#14]
Hey there,
I've noticed a bug that's driving me crazy: Whenever I'm using the microphone via https://app.schildi.chat, Firedragon just completely slows down and clicking on a tab and interacting with websites is very slow (I click on a tab, the url changes and 10 seconds later the website appears...) - One cpu core is always at 80% while this is happening
I have verified the problem to exist on https://senfcall.de as well.
Why is this happening - I'm so confused.
Thanks!

**Comment by dr460nf1r3** [comment]
Hey there! :) Could you try removing/moving to another dir  `/use/lib/firedragon/firedragon.cfg` and restarting the browser? This could give some hints about whether it's a configuration issue or something else. If it's an issue with `firedragon.cfg` we could start finding out which value causes this behaviour exactly :)

**Comment by UltraBlackLinux** [comment]
I can confirm that the issue still persists after renaming the config.

**Comment by UltraBlackLinux** [comment]
I have no clue what the "Tabs sharing devices" tab is at all, but I clicking on it opens a *little* overlay with the size of my whole screen including hundrets of "app.schildi.chat (microphone)" - Is this the issue?

**Comment by UltraBlackLinux** [comment]
[Tab stash](https://addons.mozilla.org/en-US/firefox/addon/tab-stash/) seems to slow down firefox beyond usability as well, while the tabs are loading. This is weird

**Comment by dr460nf1r3** [comment]
Thanks for your answers! I tried to reproduce the issue on app.schildi.chat but the page is working just fine here. Any special steps to take to reproduce? 
"Tabs sharing devices" could be related to the sync function of FireDragon, although I'm not sure. Feel free to add a screenshot, if you want :)

**Comment by UltraBlackLinux** [comment]
> Thanks for your answers! I tried to reproduce the issue on app.schildi.chat but the page is working just fine here. Any special steps to take to reproduce? "Tabs sharing devices" could be related to the sync function of FireDragon, although I'm not sure. Feel free to add a screenshot, if you want :)

Weird. Meanwhile I was able to reproduce the issue with a new profile...

**Comment by UltraBlackLinux** [comment]
I give up, firefox based browsers seem to suck - I'm switching to brave even though chromium based browsers have the worst addons on the planet and are plagued by censoring and whatnot by google... I miss the account containers already.

I guess You may close this if you want to, I will keep it open in case someone arrives here soon
