### ISSUE TITLE
firedragon-hg Fails to Launch

### ISSUE THREAD

**Issue by MetalNeo** [dr460nf1r3/firedragon-browser#16]
`firedragon-hg` is failing to launch after being installed. The error below appears when being launched. Application was installed from the Chaotic AUR.

```
Netscape.cfg/AutoConfig failed. Please contact your system administrator. 
 Error: defaultPref failed: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.setBoolPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: prefcalls.js :: defaultPref :: line 60"  data: no]
```

**Comment by dr460nf1r3** [comment]
Hey! :) The package is in need of a rebuild but fails to compile currently. The package has been pulled temporarily, I'd suggest using the stable one for the time being.
