### ISSUE TITLE
Firedragon Defaults to Incorrect Value for browser.contentblocking.category

### ISSUE THREAD

**Issue by MetalNeo** [dr460nf1r3/firedragon-browser#17]
Firedragon is defaulting pref `browser.contentblocking.category` to `custom` instead of the value listed in the cfg file, `strict`. Manually setting the pref causes it to revert back to `custom` on browser restart.

Tested on Garuda Linux using Firedragon package from the Chaotic AUR.

**Comment by dr460nf1r3** [comment]
The `.cfg` isn't the only thing setting the pref though. Have a look at `/usr/lib/firedragon/distribution/policies.json` - in here we also have policies concerning "EnableTrackingProtection". I'd try removing that part to see if it sticks afterwards.

**Comment by MetalNeo** [comment]
Thank you so much! I had a feeling that the setting was being set/edited elsewhere. After removing those lines, Firedragon correctly defaulted to the `strict` setting.

I'll get a PR set up to close this issue shortly.

**Comment by dr460nf1r3** [comment]
Thanks! :)
