### ISSUE TITLE
How come  websites aren't taking up the entire window?

### ISSUE THREAD

**Issue by amarakon** [dr460nf1r3/firedragon-browser#2]
For some reason websites only take up around 90% of the space of the window. But I want them to take up the entire window like they would in every other web browser. How can I change it to do that. It's probably something in the about:config section, but I don't know what.

**Comment by dr460nf1r3** [comment]
This is most likely an anti-fingerprinting measure which makes sure that browser window size is nothing out of the ordinary. `privacy.resistFingerprinting` is the value in question.

**Comment by amarakon** [comment]
Okay. I am going to set privacy.resistFingerprinting to false and replace it with a fingerprint blocking add-on. If that solves the issue, I will close this issue.

**Comment by amarakon** [comment]
Unfortunately turning off privacy.resistFingerprinting didn't do anything, even after restarting the browser.

**Comment by Thorin-Oakenpants** [comment]
letterboxing is (currently) independent of RFP
```
user_pref("privacy.resistFingerprinting.letterboxing", true); // [HIDDEN PREF]
```

**Comment by dr460nf1r3** [comment]
Does that solve your issue @amarakon ?
