### ISSUE TITLE
URL linked in settings is 404

### ISSUE THREAD

**Issue by ShalokShalom** [dr460nf1r3/firedragon-browser#20]
See this: 

![Screenshot_8](https://user-images.githubusercontent.com/6344099/156266582-e174b545-6c5f-4445-acee-4c51980e8449.png)

When you click the link: https://forum.garudalinux.org/c/issues-assistance/firedragon-browser-support/47drm-content

**Comment by dr460nf1r3** [comment]
Interesting, apparently the URL is hardcoded to `supporturl/drm-content` 🧐 I'll need have a look at how Librewolf handles that.

**Comment by dr460nf1r3** [comment]
Fixed in https://github.com/dr460nf1r3/firedragon-browser/commit/605d4cef46c3b664e34213550813100eb7ffb66b
