### ISSUE TITLE
Browser theme reverts to Sweet Dark after each update

### ISSUE THREAD

**Issue by 4qx** [dr460nf1r3/firedragon-browser#23]
Every time there's an update the theme gets switched to Sweet Dark. Something's gotta be done about that for those of us who prefer classic Dark... or any other theme I guess.

**Comment by dr460nf1r3** [comment]
Remove the following line in `/usr/lib/firedragon/distribution/policies.json`:

> "https://addons.mozilla.org/firefox/downloads/file/3365502/sweet_dark-4.0-an+fx.xpi",

To make it stick across updates, creating a Pacman hook could be helpful. Either copy the modified one in place or use something like `sed` to remove it from the original file :)
