### ISSUE TITLE
"Learn more" in SSL certification page 

### ISSUE THREAD

**Issue by ShalokShalom** [dr460nf1r3/firedragon-browser#24]
See this link: https://accounts.ea.com/

It leads, at least now and for me, to a SSL certification page:

![Screenshot_60](https://user-images.githubusercontent.com/6344099/156918892-bc8d5405-ebc8-4e1b-a82b-a9a3997fe834.png)

And if I click this link, that is the page I get to: 
https://forum.garudalinux.org/c/issues-assistance/firedragon-browser-support/47connection-not-secure

**Comment by dr460nf1r3** [comment]
Should also be fixed in https://github.com/dr460nf1r3/firedragon-browser/commit/605d4cef46c3b664e34213550813100eb7ffb66b
