### ISSUE TITLE
Netflix not playing 

### ISSUE THREAD

**Issue by ShalokShalom** [dr460nf1r3/firedragon-browser#26]
I enabled DRM here: 

![Screenshot_84](https://user-images.githubusercontent.com/6344099/157310846-ee372b40-dc45-47cf-b697-9814fcc2dd94.png)

That didnt help. Yes, Widewine is enabled (by default)

![Screenshot_87](https://user-images.githubusercontent.com/6344099/157310889-f442e974-e197-4a03-a35b-e54fa5ab3cd6.png)

Then, I changed the override file. **It was still set to false.** 

![Screenshot_89](https://user-images.githubusercontent.com/6344099/157310947-71fe7421-2f1a-4e32-9744-d67cd434a53a.png)

It still did not enable Netflix play. Any other ideas? (Works on Chrome)

**Comment by dr460nf1r3** [comment]
While trying to find a solution I stumbled upon this [Librewolf thread](https://gitlab.com/librewolf-community/browser/linux/-/issues/261#note_743205774) which was in fact dealing with the exact same issue. Check out the supposed solution and let me know if it works for you :)

**Comment by ShalokShalom** [comment]
Well, can we make this default? As far as I understand, it requires removing security features, but maybe we can link this setting behind the "Enable DRM" setting, so this actually works?

The other method is to let every user run into this, a small fraction of them come here, an ever smaller fraction decide to change those settings, probably an even smaller fraction is successful at this..

**Comment by dr460nf1r3** [comment]
While I think changing the browser agent to mimic Firefox for various websites is a good idea, I don't want to turn off anti fingerprinting measures. After all, we are privacy focused here :)

**Comment by ShalokShalom** [comment]
Yeah, and my first attempt to launch Netflix, was to install Chrome.
Let people choose. Since you are about choice as well ;)

**Comment by ShalokShalom** [comment]
So, when I set privacy.resistFingerprinting to false, the error screen changes to this: 

![Screenshot_147](https://user-images.githubusercontent.com/6344099/158800180-5bb779ce-4cbd-437c-880a-63b84601a951.png)

Naturally, changing the user agent now would suggest that it works. But it doesnt: 

I tried this with different useragent strings, including that one mentioned in the Gitlab issue. 

But changing the useragent, did work for other features like the [WhatsApp](https://github.com/dr460nf1r3/firedragon-browser/issues/27) client.

**Comment by dr460nf1r3** [comment]
Try using a completely fresh profile and just do these 2 modifications. That's how I did it and it worked.

**Comment by ShalokShalom** [comment]
Well, do you consider this how every user is supposed to do it? 

Whenever something dont work, just delete your whole configuration and then do some work in about:config? 

As said, nobody will do that. Who is slightly interested into a smooth experience. I would rather use another browser.

**Comment by dr460nf1r3** [comment]
Me being the only one working on this browser unfortunately means that I can't test every single modification needed for specific websites myself - that's why I'm providing some instructions on how to to investigate things rather than ignoring your request, if that's too much to ask for I'm sorry. You could even use another browser just for Netflix, if that's a deal breaker for you.

If you are interested in 100% working websites I'd suggest going with plain Firefox or even Chrome, this will provide exactly what you seem to be looking for. 

Certain things have been adapted for "greater masses" in the past already and I'm completely fine with that. However, I won't drop anti fingerprinting because of given reasons. Heck, if people want to use another browser that's okay, after all FOSS is also about having and making choices 🙂 

Cheers!

**Comment by ShalokShalom** [comment]
Dropping anti fingerprinting on request. When somebody presses "Enable DRM" that's an indicator, that this person prefers Netflix over said privacy. 

Just an suggestion :)

**Comment by dr460nf1r3** [comment]
You might have noticed that there is a toggle for this in Firedragon settings already 🙃

**Comment by ShalokShalom** [comment]
Yeah. And its not working. I mean, that the DRM button disables resistFingerprinting. As it is now, enabling the DRM button does nothing.
