### ISSUE TITLE
EA Account

### ISSUE THREAD

**Issue by ShalokShalom** [dr460nf1r3/firedragon-browser#28]
The login fails in FireDragon, and it works in Chrome. 
Says it is SSL related. 

https://www.ea.com/ (Top right button for the account login)

**Comment by fxbrit** [comment]
hint -> https://librewolf.net/docs/faq/#im-getting-the-ssl_error_unsafe_negotiation-error-what-can-i-do

**Comment by dr460nf1r3** [comment]
Yup, follow the guide and set the config accordingly - it will let you login. :)
