### ISSUE TITLE
Librewolf typo in Settings menu

### ISSUE THREAD

**Issue by FGD-Garuda** [dr460nf1r3/firedragon-browser#29]
Hi there,

`firedragon_98.0.2-3`

Since it isn't the 1st time I see this typo I am opening an issue this time so it can be addressed for future releases. :)

When you open Firedragon and open `Settings` from the hamburger menu, you are greeted on the left-hand side with this funny typo, proof that Firedragon is a fork of Librewolf. lolll :)

![Screenshot_1](https://user-images.githubusercontent.com/35015576/161448770-273fbfa6-e8c1-4576-8105-83c9234471e9.png)

I have seen improvements in the browser in the past 3 months, keep the good work!

**Comment by dr460nf1r3** [comment]
Hey :) I forgot patching the patch here 😅 a new fixed build will be pushed this evening :)

**Comment by dr460nf1r3** [comment]
A new build just started! I implemented [automated rebranding](https://gitlab.com/dr460nf1r3/common/-/blob/master/rebrand.sh) during the build process so I don't need to watch things anymore 😁

**Comment by FGD-Garuda** [comment]
Fixed!
`98.0.2-4`

> I implemented [automated rebranding](https://gitlab.com/dr460nf1r3/common/-/blob/master/rebrand.sh) during the build process so I don't need to watch things anymore 😁

Nice touch! :D
