### ISSUE TITLE
Can't login gitlab.com

### ISSUE THREAD

**Issue by shawanroy** [dr460nf1r3/firedragon-browser#3]
Can't login on https://gitlab.com/. Auto reloading the page every time. Tested on VPN and Normal Internet, all have same result, can't redirect to login page even on private browsing mode. I think problem on firedragon special settings, which creates this issue. Other Firefox, Chromium browser works fine. Please solve this problem.
Screenshot link: [](https://i.imgur.com/GVJcuE3.png)
Thanks & Regards

**Comment by dr460nf1r3** [comment]
According to the linked issue the [problem is solved ](https://gitlab.com/gitlab-com/www-gitlab-com/-/issues/12422#note_718149297)!
