### ISSUE TITLE
YouTube tab crashes consistently in version 100.0.1-1

### ISSUE THREAD

**Issue by vinivosh** [dr460nf1r3/firedragon-browser#32]
Found a bug that's making YouTube unusable in version 100.0.1-1. Downgrading to 100.0-2 solved the issue entirely.

Youtube tabs keep crashing when performing the following actions:
- Hovering a video's title or thumbnail. Doesn't happen with some videos, for some reason, but happens with the vast majority
- Clicking a video's title or thumbnail
- Clicking the notifications icon (the bell besides your user photo in the top right corner)

At first I thought it was some extension I use, like [CanvasBlocker](https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/) or [Enhancer for Youtube](https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/). But even after disabling all my extensions, this still happens consistently.

Here is the console output when the crash happens:

```
Gtk-Message: 12:58:18.418: Failed to load module ""canberra-gtk-module"
Gtk-Message: 12:58:18.418: Failed to load module "atk-bridge""
console.error: BroadcastService:
  receivedBroadcastMessage: handler for
  remote-settings/monitor_changes
  threw error:
  Message: Error: Polling for changes failed: The URI is malformed..
  Stack:
    remoteSettingsFunction/remoteSettings.pollChanges@resource://services-settings/remote-settings.js:254:13

[2022-05-22T15:58:22Z ERROR mp4parse] Found 2 nul bytes in "\0\0"
[2022-05-22T15:58:22Z ERROR mp4parse] Found 2 nul bytes in "\0\0"
[2022-05-22T15:58:22Z ERROR mp4parse] Found 2 nul bytes in "\0\0"
[2022-05-22T15:58:22Z ERROR mp4parse] Found 2 nul bytes in "\0\0"
[2022-05-22T15:59:07Z ERROR mp4parse] Found 2 nul bytes in "\0\0"
[2022-05-22T15:59:07Z ERROR mp4parse] Found 2 nul bytes in "\0\0"
[2022-05-22T15:59:07Z ERROR mp4parse] Found 2 nul bytes in "\0\0"
[2022-05-22T15:59:07Z ERROR mp4parse] Found 2 nul bytes in "\0\0"

###!!! [Parent][PImageBridgeParent] Error: RunMessage(msgname=PImageBridge::Msg_WillClose) Channel closing: too late to send/recv, messages will be lost
```

All I did here was open Firedragon, let a YT video page load, select some comments' text, like some comments, then hover some videos in the recommendations section. Only when I hovered the third video the crash happened. Then I restored the tab and repeated the same steps, and it crashed again. I was logged in, too.

**Comment by dr460nf1r3** [comment]
Hey! There has been an update to 100.0.2, please let me know if the improves things :)

**Comment by vinivosh** [comment]
> Hey! There has been an update to 100.0.2, please let me know if the improves things :)

Wow, the update seems to have fixed it perfectly! I'll test it on some more videos and close the issue tomorrow if I don't find anything else. Thanks!

**Comment by vinivosh** [comment]
I'm afraid the Issue reappeared in 100.0.2-3

**Comment by dr460nf1r3** [comment]
It's actually the same issue: https://github.com/chaotic-aur/packages/issues/1444#issuecomment-1140510506

**Comment by dr460nf1r3** [comment]
I got reports that the latest version works better (fixed PGO)
