### ISSUE TITLE
Privacy redirect doesnt open freetube properly

### ISSUE THREAD

**Issue by Arndorferd** [dr460nf1r3/firedragon-browser#33]
Privacy redirect is able to work to open using freetube redirect which is in its invidious settings on librewolf and firefox but not firedragon.

I opened a [request](https://github.com/SimonBrazell/privacy-redirect/issues/384) with privacy redirect as well.

**Comment by Arndorferd** [comment]
the freetube://youryoutubeURL.com command specifically is whats giving trouble as thats what it uses, freetube doesn't register the command, do you know why this would not work on firedragon but would work on librewolf?

**Comment by dr460nf1r3** [comment]
Confirmed issue!

**Comment by Arndorferd** [comment]
closed privacy redirect [request](https://github.com/SimonBrazell/privacy-redirect/issues/384) because this is either a firedragon or freetube issue. I have a [request](https://github.com/FreeTubeApp/FreeTube/issues/2272) at freetube, however since this works in librewolf Im guessing its not with them either.

**Comment by dr460nf1r3** [comment]
Yeah, I'd also say its certainly FireDragon related.
