### ISSUE TITLE
Wayland Plasma - Youtube Contextual Menus sometimes disappear on hover only in "Watch later" video list

### ISSUE THREAD

**Issue by FGD-Garuda** [dr460nf1r3/firedragon-browser#38]
Hi there!

I have a tough one for you. :)

- Firedragon 102.0-2
- Plasma 5.25.2 w/Wayland
- AMD card using `amdgpu` `radeon` `nouveau`

The issue does not happen at all with original Firefox 102.0.1-1.
It also does not happen with Firedragon when using XWayland protocol, nor X11 protocol.

However when running Firedragon under Wayland Window Protocol (using `MOZ_ENABLE_WAYLAND=1` in `envvars.conf` user file - https://wiki.archlinux.org/title/Firefox#Wayland and https://wiki.archlinux.org/index.php/Environment_variables#Graphical_environment) and you go into your Youtube list of videos you have tagged for later viewing, when you right-click on the video title most of the time, but not ALL the time, the Plasma contextual menu disappears as soon as your mouse pointer navigates within the menu, so that no selection can be toggled, not even the 1st one on top.

I found out this seems to happen mostly on the videos listed at the end of the list shown on screen, but I can also make it break on videos at the top of the list on screen, although much less often.
It does not happen in any other Youtube pages.

That's a very weird one and I have totally no idea what data to provide for troubleshooting. :(
However I know there's a trick with Firedragon and KDE Integration so maybe it lies somewhere in there...

Sure I could test Librewolf and see if it happens there too?

Thanks

**Comment by dr460nf1r3** [comment]
Hey :) testing this on Librewolf would indeed give valuable hints on how to go on with this 👀

**Comment by FGD-Garuda** [comment]
LOLLLL Ok well I found the problem. And what a weird problem it is...

What triggers this weird issue is the precise use of the following environment variable `GDK_DPI_SCALE=1.3`.

Whenever I launch Firedragon, or Librewolf, no matter the Profile I use (even new one!), with the following command `GDK_DPI_SCALE=1.3 firedragon`, it causes this contextual menu issue.

If I use 1.2, or 1.4, there's no issue.
And the funniest part is, you guessed it, 1.1 is too small for my taste and 1.4 too big. What a bummer! lolll

I have seen a lot of weird issues on Linux but not one like this.
I will accept to find a way to work around it, as I don't believe I will ever get close to identify why the scaling value 1.3 is causing the issue....

Oh well, I am closing this. :D

**Comment by dr460nf1r3** [comment]
I'm glad to hear you found the solution! I guess I never would've found out that this was causing the whole situation. Your troubleshooting skills seem to be pretty good 😜
Cheers!
