### ISSUE TITLE
Firedragon doesn't completely compile on Arch Linux (AUR)

### ISSUE THREAD

**Issue by ardishco-the-great** [dr460nf1r3/firedragon-browser#39]
Here are the logs.

```
Hunk #1 FAILED at 1269.
1 out of 1 hunk FAILED -- saving rejects to file browser/components/BrowserGlue.jsm.rej
patching file browser/components/moz.build
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: firedragon

```

Can provide more If required but I thought these were the root of the problem

**Comment by ardishco-the-great** [comment]
Oh...That's an unofficial package. I'm sorry if anyone got confused by this.

I just used chaotic-aur and it worked.

**Comment by dr460nf1r3** [comment]
It's actually the official PKGBUILD, patches are failing because it needs to be updated to v103. This will happens once all needed patches got updated :)
