### ISSUE TITLE
Can't restore sync functionality

### ISSUE THREAD

**Issue by parsifallo** [dr460nf1r3/firedragon-browser#4]
Hey!

I am currently trying to restore sync functionality but with no success. I created a `~/.firedragon/firedragon.overrides.cfg` file and added:
```
unlockPref("identity.fxaccounts.enabled","");
pref("identity.fxaccounts.enabled",true);

unlockPref("identity.sync.tokenserver.uri", "");
pref("identity.sync.tokenserver.uri", "https://<privateURI>/token/1.0/sync/1.5")
```

After restarting FireDragon I have the "Sign In" Button back, but nothing happens after I log in. What am I missing here?

BR
parsi

**Comment by dr460nf1r3** [comment]
Hey there, I'm quite sure there are more values to change when trying to enable accounts & syncing.
I would advise to subsequently trying to find out which ones are needed by commenting out the main firedragon.cfg in /usr/lib/firedragon :)

**Comment by dr460nf1r3** [comment]
Syncing functionality is back since the latest build. We don't use Mozillas servers however, instead our own selfhosted syncserver is utilized. It's easy enough to change this back to Mozillas servers though, have a look at this commit for [reference](https://gitlab.com/dr460nf1r3/settings/-/commit/6e6226d8776f8ba199906c0f316af96ce8c2f9ba#30b6f0dd77e6fb5baae56412a6982ff9ef96324a_488_487)

**Comment by dmp1ce** [comment]
By default, syncing isn't working for me. I don't have any `~/.firedragon/*.cfg` as of yet.

I sign into sync but the menu never says I'm signed in and I don't have any of by bookmarks I had synced from Firefox. This is the first time I'm using Firedragon.

**Comment by dr460nf1r3** [comment]
Hey there, it seems you found a bug as I could replicate this behaviour. Weird thing though, it was fixed for a time after adding [this](https://gitlab.com/dr460nf1r3/settings/-/commit/1103f22c3d4ea64ed33ee6be0acb03a7ad634466) commit 👀 I'll try to find out what's happening at the weekend.

**Comment by dr460nf1r3** [comment]
The issue has been fixed today! :)

**Comment by dmp1ce** [comment]
I think I have the new version but FireDragon still says "Sync and save data" when I check if I am signed into Firefox sync.
![Not synced for me 2022-01-18 06-39-33](https://user-images.githubusercontent.com/58784/149930777-e19ed0d8-e458-4c4a-8e01-0d8f7e50bdb5.png)

**Comment by dr460nf1r3** [comment]
Version 96.0.1 is the current version, although 96 already had the changes. Do you build the browser yourself or do you get it from Chaotic-AUR?

**Comment by dmp1ce** [comment]
I'm using Chaotic-AUR.
![Firedragon version 2022-01-18 06-58-34](https://user-images.githubusercontent.com/58784/149933476-07d47fc9-7036-41c1-b4e3-3dee174df4a9.png)

**Comment by dmp1ce** [comment]
```
λ pacman -Qs firedragon
local/firedragon 96.0-2
    Librewolf fork build using custom branding, settings & KDE patches by OpenSUSE
```

**Comment by dr460nf1r3** [comment]
Are there any .pacsave/.pacnew files by chance? Could you try creating a fresh profile and trying to sign in with this? That is how I tested if logging in works.

**Comment by dmp1ce** [comment]
I don't think I have any .pacsave/.pacnew files. I tried `pacdiff -o`. How do I do a new profile?

**Comment by dr460nf1r3** [comment]
Enter `about:profiles`, click create new and then start this profile :)

**Comment by dmp1ce** [comment]
I tested with a brand new profile and I still couldn't verify I was signed in. Same thing as in this image. https://github.com/dr460nf1r3/firedragon-browser/issues/4#issuecomment-1015329741

**Comment by dr460nf1r3** [comment]
Okay, very weird. I'll dig a little deeper, thanks for your time! :)

**Comment by Goldenfreddy0703** [comment]
Hey there, sorry for bothering but im also having this issue and whenever i sign in, nothing happens. I tried running firedragon in troubleshoot mode and signing in and it worked but when i go out of trouble shoot mode, nothing is syncing and idk why?

**Comment by dr460nf1r3** [comment]
Okay, that's a helpful comment I guess. It's on my to-do list, I'm just pretty busy with real life atm 🙁

**Comment by Goldenfreddy0703** [comment]
Ahh I understand, I found a workaround by downloading Firefox, syncing everything, and transferring my Firefox profile to Firedragon and that helped restore everything. Syncing is still having a problem though but hopefully, it will be fixed someday.

**Comment by dr460nf1r3** [comment]
Could you try removing the ClearURLs addon and trying to login then?

**Comment by Goldenfreddy0703** [comment]
Hey I can try that tommawow, I'm on windows and I need to go to Linux soon once I'm done.

**Comment by dmp1ce** [comment]
@dr460nf1r3 , Yes, disabling ClearURLs allowed me to login to Firefox Sync.

**Comment by dr460nf1r3** [comment]
So the config wasn't the culprit after all, very good to know! That also means we will need to remove this addon from the browser, can't have something breaking basic functionality. Thanks for being patient and reporting back, cheers! 😸
