### ISSUE TITLE
privacy.resistFingerprinting acts like inverted

### ISSUE THREAD

**Issue by Enerccio** [dr460nf1r3/firedragon-browser#40]
I had issues with canvas being blocked so I set "privacy.resistFingerprinting" to false to disable it but it breaks previously working websites such as google.com giving me "unsupported version".

**Comment by dr460nf1r3** [comment]
I'd assume its because the real browser agent isn't recognized by Google. Try overriding it by setting the following in `about:config`: 
- `general.useragent.override` with value `Mozilla/5.0 (Windows NT 10.0; rv:103.0) Gecko/20100101 Firefox/103.0`

**Comment by Enerccio** [comment]
That's it!

**Comment by dr460nf1r3** [comment]
Nice! :)
