### ISSUE TITLE
Make this translationable

### ISSUE THREAD

**Issue by olivertzeng** [dr460nf1r3/firedragon-browser#42]

**Comment by Technetium1** [comment]
https://github.com/dr460nf1r3/firedragon-browser/blob/01e234b7876f644389791d52a60fc165e6afe5e8/firedragon.cfg#L261-L269
Change this if you need to change language I think. Also check this out: https://gitlab.com/librewolf-community/browser/windows/-/issues/64

**Comment by olivertzeng** [comment]
ok thanks!
