### ISSUE TITLE
Offer Flatpak Version

### ISSUE THREAD

**Issue by That-Human-Being** [dr460nf1r3/firedragon-browser#43]
I recently got a Steam Deck and would like to have Firedragon there over Firefox/Librewolf mostly due to the better KDE integration, could either you offer builds on Flathub or I'm fine with setting up additional remotes? I really only asking because I'd prefer getting all of my non-Steam software through Flatpak remotes on my deck than elsewhere.

**Comment by dr460nf1r3** [comment]
Hey :) Cool to see Steam Deck users wanting to use FireDragon! AppImage builds also got [requested some time back](https://github.com/dr460nf1r3/firedragon-browser/issues/35#issuecomment-1157584373) but I couldn't get to implement those either yet. However, I'm always open to contributions :)

**Comment by Technetium1** [comment]
This is related to #30

**Comment by ThousandDemonDaggers** [comment]
Since the flatpak is now available, shouldn't this issue be closed?
