### ISSUE TITLE
Binaries for AUR

### ISSUE THREAD

**Issue by EpicGamer007** [dr460nf1r3/firedragon-browser#44]
Hi!
I was wondering if there are any plans to bring prebuilt binaries to the AUR? Something like [firedragon-bin](https://aur.archlinux.org/packages/firedragon-bin). I would rather not add chaotic aur to my repository list (it also requires multilib which i would not prefer) and compiling on my system is not entirely suitable either.
Thanks =)

**Comment by Technetium1** [comment]
I wouldn't count on it, but I'm not in a position to give the final answer. You don't need to use multilib if it's _**only**_ going to be used for this package! We say that because many packages require some 32 bit dependencies, which I don't believe any of FireDragon's are. The package database for Chaotic is only 2019.4 KiB, so it's not really an impact on updates.

```
Depends On      : gtk3  libxt  mime-types  dbus-glib  nss  ttf-font  libpulse  ffmpeg  kfiredragonhelper

Optional Deps   : firejail-git: Sandboxing the browser using the included profiles
profile-sync-daemon: Load the browser profile into RAM [installed]
whoogle: Searching the web using a locally running Whoogle instance
searx: Searching the web using a locally running searX instance
networkmanager: Location detection via available WiFi networks [installed]
libnotify: Notification integration [installed]
pulseaudio: Audio support [installed]
speech-dispatcher: Text-to-Speech
hunspell-en_US: Spell checking, American English [installed]
libappindicator-gtk3: Global menu support for GTK apps [installed]
appmenu-gtk-module-git: Appmenu for GTK only
plasma5-applets-window-appmenu: Appmenu for Plasma only [installed]
```

**Comment by EpicGamer007** [comment]
I see.. I am not very knowledgeable about chaotic aur but would it not be possible to setup a PKGBUILD which points to a binary in the chaotic aur? Something like `https://aur.chaotic.cx/firedragon-browser-{arch}-{version}.tar.xz` which is fetched, then unzipped and installed?

**Comment by Technetium1** [comment]
Chaotic only hosts the [latest version of a file at any given moment](https://chaoticmirror.com/chaotic-aur/chaotic-aur/x86_64/#firedragon), and we don't currently have an automatic sync _to_ the AUR, so it would randomly break when a new build happens. I do see a chance of this happening if we ever get the sync concept fully fleshed out.

**Comment by EpicGamer007** [comment]
Thanks, hopefully automatic sync comes sometime soon. Would be very useful 👍 Closing issue

**Comment by dr460nf1r3** [comment]
> I see.. I am not very knowledgeable about chaotic aur but would it not be possible to setup a PKGBUILD which points to a binary in the chaotic aur? Something like `https://aur.chaotic.cx/firedragon-browser-{arch}-{version}.tar.xz` which is fetched, then unzipped and installed?

Already did this in the past, the package got deleted due to "not following guidelines" :(

**Comment by EpicGamer007** [comment]
Very sad. Did they provide a reason as to why other than "not following guidelines"?

**Comment by Technetium1** [comment]
I'd suspect it was one of the 'unwritten' rules. My only guess is that it might not have had `-bin`.

**Comment by dr460nf1r3** [comment]
Iirc it got deleted due to using the existing Chaotic-AUR package as source - I can't understand the logic behind this. Other -bin packages use artifacts built by some CI tool, Chaotic-AUR is not really different. If it's about the build logs, these are in fact available as well 🙄

**Comment by EpicGamer007** [comment]
Either way, just wanted to let you know i have added choatic-aur (very easily) and have been using this borwser primarily for the past month. Love it a lot :heart:

**Comment by dr460nf1r3** [comment]
I'm glad you like it :heart:
