### ISSUE TITLE
Instagram live shows all black screen, only audio can be heard. 

### ISSUE THREAD

**Issue by parthrusia** [dr460nf1r3/firedragon-browser#45]
Don't know what else to include here.

**Comment by Technetium1** [comment]
Have you tried disabling any extensions to see if it changes?

**Comment by dr460nf1r3** [comment]
Also, you could try turning off resist fingerprinting in the firedragon settings.

**Comment by parthrusia** [comment]
> Also, you could try turning off resist fingerprinting in the firedragon settings.

This worked. Disabling resist fingerprinting solved the problem.

**Comment by dr460nf1r3** [comment]
Glad to hear you got it solved.
