### ISSUE TITLE
Redundant? (ClearURLs)

### ISSUE THREAD

**Issue by OkyDooky** [dr460nf1r3/firedragon-browser#46]
I saw on the project page that ClearURLs is included, but [looking at the Arkenfox wiki](https://github.com/arkenfox/user.js/wiki/4.1-Extensions) it seems that uBlock Origin already handles that task, when you turn on the AdGuard URL Tracking Protection list and import the Actually Legitimate URL Shortener Tool list, both of which LibreWolf sets up by default.

Would it make sense to just ditch ClearURLs or does it actually provide something more than what those lists give?

**Comment by Technetium1** [comment]
Seems to do more than the generic lists uBlock Origin can provide, I use both.

**Comment by OkyDooky** [comment]
That would be cool to have confirmed. I don't want to completely deprecate an add-on, but it's parameters could be added to one of the lists (like the Actually Legitimate URL Shortener). Maybe I could open an issue there, if that's the case.

**Comment by dr460nf1r3** [comment]
The `removeparam` part was interesting, i didn't know about this before 👀 now I wonder whether pre-altering addon settings is somehow possible 🤔

**Comment by dr460nf1r3** [comment]
I'll have a look, if it's possible we might as well drop clearurls - nice suggestion :)

**Comment by OkyDooky** [comment]
Thanks! Hope it does work out. Looking forward to seeing where this issue goes and the future of this browser/fork. :)

**Comment by dr460nf1r3** [comment]
I don't get how they actually make it work. The custom patch is already added but seems to have no effect on FireDragon. Also, I can't find the any sign of the custom asset being added in Archlinux's PKGBUILD for Librewolf - any idea?

**Comment by OkyDooky** [comment]
Yo! Just installed Garuda and noticed the lack of ClearURLs. Did it get removed?
Also, no, I don't have any udeas. I'm not familiar with how they make their stuff. Have you tried asking the LW developers directly? I'd assume it'd be more something on their end than Arch-specific. 🤔

**Comment by Technetium1** [comment]
I spent a while looking and I don't see it anywhere either :eyes: 
There is this where it's mentioned though...
https://gitlab.com/librewolf-community/website/-/merge_requests/5

**Comment by dr460nf1r3** [comment]
> Yo! Just installed Garuda and noticed the lack of ClearURLs. Did it get removed?
> Also, no, I don't have any udeas. I'm not familiar with how they make their stuff. Have you tried asking the LW developers directly? I'd assume it'd be more something on their end than Arch-specific. 🤔

Oh yes, I need to update the readme! 🤔 iirc it caused issues with syncing.

**Comment by dr460nf1r3** [comment]
> I spent a while looking and I don't see it anywhere either :eyes: 
> There is this where it's mentioned though...
> https://gitlab.com/librewolf-community/website/-/merge_requests/5

It's almost as it didn't exist 😂👀

**Comment by OkyDooky** [comment]
Haha, cool. So, I guess this issue can be closed, since it seems every point was accomplished, then?
Also, I hope you get the mysteries of LibreWolf resolved soon!
