### ISSUE TITLE
[enhancement] Add kill-sticky bookmarklet by default

### ISSUE THREAD

**Issue by Technetium1** [dr460nf1r3/firedragon-browser#47]
I think it's possible to set a default bookmark, so why not a convenient bookmarklet too?
https://github.com/t-mart/kill-sticky

**Comment by dr460nf1r3** [comment]
I didn't see this request earlier 👀 actually that's a pretty great idea! Non-intrusive and still coming in handy :)

**Comment by dr460nf1r3** [comment]
Mhm, looking at it the bookmarks are currently set via `garuda-browser-settings` here. Would you be fine with adding it there?

**Comment by Technetium1** [comment]
Definitely! I wonder if there's a way to non-invasively mark the version at the moment for updating in the future.

**Comment by dr460nf1r3** [comment]
For now, here is the commit containing the addition: https://gitlab.com/garuda-linux/themes-and-settings/settings/garuda-browser-settings/-/commit/949865a94ed0d7ce65f98825587289f6e104c461
