### ISSUE TITLE
Latest Update Causes weird font behaviour

### ISSUE THREAD

**Issue by EpicGamer007** [dr460nf1r3/firedragon-browser#48]
Hi, a recent update from chaotic aur (`105.0.3-1`) has caused fonts to behave very weirdly such that they are extremely blurry. Can confirm this does not happen with firefox, librewolf, or tor browser so this appears to be a firedragon specific issue.
![image](https://user-images.githubusercontent.com/80220229/194732344-e8d8c58b-f5d4-41dd-9576-a5bac66b48c5.png)

Thanks

Edit: For clarification, fonts look pixelated.
![image](https://user-images.githubusercontent.com/80220229/194732363-da585ead-c97c-47d3-8272-0fbb119b776c.png)

**Comment by Technetium1** [comment]
Here's what I have as my defaults, what do you have?
Settings -> General -> Fonts -> Advanced
![image](https://user-images.githubusercontent.com/9877150/194733989-89842fe4-3ebd-43a2-b013-eb871851deb7.png)

**Comment by EpicGamer007** [comment]
![image](https://user-images.githubusercontent.com/80220229/194739457-baf32759-88b8-4524-a4b9-fc53e3f600b4.png)

**Comment by EpicGamer007** [comment]
https://user-images.githubusercontent.com/80220229/194741100-d6c892ed-ee4b-4d51-8577-23cff8fb1eef.mp4


After some experimenting, I found that the environment variable `GTK_USE_PORTAL="1"` was the cause for this issue. I am not sure what exactly it those but it was on by default in the KDE Application Command. Removing that solves this issue. Not sure why it happens though.

**Comment by Technetium1** [comment]
That's incredibly strange. I wonder, does that happen for Librewolf?

**Comment by EpicGamer007** [comment]
This issue isn't present in tor browser (but it uses firefox version 91)

https://user-images.githubusercontent.com/80220229/194776562-ab8d0a82-3b8d-40cf-abcc-a2937fc37de6.mp4

This appears to be an upstream issue though.
Both Firefox and Librewolf have this issue (Video only shows firefox but it is applicable to both applications)

**Comment by dr460nf1r3** [comment]
https://github.com/dr460nf1r3/firedragon-browser/commit/289067a9be122fd396db32ef0043796193946ffe the portals were enabled here in order to get rid of a patch that was required to achieve KDE Filepicker usage before.

**Comment by EpicGamer007** [comment]
DE: KWin
Hardware
* HP Laptop 15t-dy200
* 16 GB Ram
* 5.19.13-arch1-1 kernel
* CPU: 11th Gen Intel i7-1165G7 (8) @ 4.700GHz
* GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics]

In regards to the KDE Filepicker, I am able to achieve the native file picker with and without the environment variable.

**Comment by dr460nf1r3** [comment]
As of the latest build, the file picker is enabled by this https://github.com/dr460nf1r3/firedragon-browser/commit/289067a9be122fd396db32ef0043796193946ffe#diff-3eb779079ad4346f8eade242846d429257510d13ca279c6f4a645258b5f327f3R544, no environment variable needed anymore!
