### ISSUE TITLE
No YouTube live chat after latest update

### ISSUE THREAD

**Issue by l4kr** [dr460nf1r3/firedragon-browser#5]
Hi, it appears the chat is not working on YouTube livestreams after the latest update.
I have tried icognito aswell, same result. Works on regular Firefox and Chromium.

Steps to reproduce:
- open FireDragon
- go to any YouTube livestream

![image](https://user-images.githubusercontent.com/73653844/140536841-05022c84-16f7-4235-8aeb-71518757a471.png)

**Comment by dr460nf1r3** [comment]
Hey there! 
Could you try to put [this](https://gitlab.com/dr460nf1r3/settings/-/blob/98a9d6bcd027c5696580758daf54bcdaeeb60707/firedragon.cfg) firedragon.cfg in /usr/lib/firedragon ? I imported some upstream config changes from Librewolf. 
That being said however, I can't reproduce the issue. YouTube works for me on the latest build.

**Comment by l4kr** [comment]
Unfortunately, the file didn't help

**Comment by dr460nf1r3** [comment]
I just checked and can't reproduce the issue sadly. Livestreams as usual 👀

**Comment by l4kr** [comment]
Found a fix!

I have been playing around with the about:config page so it's possible that due to user error I might have misconfigured something.
However, I managed to get it working again by editing **general.useragent.compatMode.firefox** to **true**

**Comment by dr460nf1r3** [comment]
Glad to hear this! 
Cheers 🔥
