### ISSUE TITLE
Can't download files: GDBus.Error

### ISSUE THREAD

**Issue by thealio** [dr460nf1r3/firedragon-browser#50]
Hi
after the latest release, it's impossible to download fiels.
The error is this:

(firedragon:5808): Gtk-WARNING **: 18:22:34.601: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
I tried on bot EndeavourOS & Manjaro. On Plasma and Trinity DE
I tried to downgrade xdg-desktop-portal-kde.
But it doesn't work

Thanks in advance

**Comment by Technetium1** [comment]
Working fine for me on Garuda with the latest versions of everything...
![image](https://user-images.githubusercontent.com/9877150/196559378-0bc0f665-2392-45ae-b419-dcac11a56949.png)

**Comment by dr460nf1r3** [comment]
I can't reproduce this either sadly. 

![Uploading image.png…]()

**Comment by thealio** [comment]
Problem solved
I removed `xdg-desktop-portal` package, because it was signed as orphan
Now it works again

Suggestion : please make `xdg-desktop-portal` as a necessary dependence for firedragon
Thank you for your support

**Comment by dr460nf1r3** [comment]
Good to know you have it solved! I just added the dependency as suggested - it IS actually required since we use the portals for the file picker since like the last version? Thanks for contributing! 🐲
