### ISSUE TITLE
FireDragon filling up disk space with tons of crash recovery files

### ISSUE THREAD

**Issue by vinivosh** [dr460nf1r3/firedragon-browser#53]
The browser seems to be freezing completly at random moments. Happens like three times a day. Happened once with LibreWolf, so it may not be a FireDragon issue.

However, FireDragon is filling up a LOT of disk space with crash recovery files that each have like 600+ MB and keep increasing with time.

<img width="457" alt="image" src="https://user-images.githubusercontent.com/36175157/204152359-f82d7c98-9ec1-4304-bdea-b042fb45ff70.png">

There are 74 of these `v6dcx8vu.default-release-backup-crashrecovery*` folders here…

Is this intended behaviour? Shouldn't these be auto-deleted after a successful launch of the browser, or at least have a ceiling in occupied size in disk (like, delete after 10 files or after all files start using up more than X MB in disk, etc.)

**Comment by Avichal1234** [comment]
Did you manage to fix it?

**Comment by dr460nf1r3** [comment]
Closing due to lack of feedback. I have not read about anything like this in the meantime.
