### ISSUE TITLE
Feature request: AppImage build.

### ISSUE THREAD

**Issue by expertmanofficial** [dr460nf1r3/firedragon-browser#54]
Currently, I am using LW but I would LOVE to try FDB - however I am Linux Mint user and AppImage is best for me to use.

Please release it :-)

**Comment by dr460nf1r3** [comment]
Related to #30

**Comment by dr460nf1r3** [comment]
Solved in https://github.com/dr460nf1r3/firedragon-browser/commit/a8f6d7d4e3cd60380b0a7929529fe0c1f5863424
