### ISSUE TITLE
Unable to install unsigned extensions

### ISSUE THREAD

**Issue by stefanwimmer128** [dr460nf1r3/firedragon-browser#55]
Even after setting "xpinstall.signatures.required" to "false" in "about:config" I was not able to install an unsigned extension, which I used previously on LibreWolf using the same setting.

**Comment by dr460nf1r3** [comment]
Hey :) this is caused by [line](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=firedragon#n120), which I already contemplated removing in the past.

**Comment by stefanwimmer128** [comment]
Thanks. I changed the line and compiled it myself. Now it works.
``` sh
export MOZ_REQUIRE_SIGNING=
```
Interestingly removing the line didn't work, apparently it defaults to `1` and `0` is not valid value.

**Comment by stefanwimmer128** [comment]
FYI, since this is a security relevant change, I would not mind maintaining my own fork. I would not want to risk opening this potential security hole in a browser that is installed by default on all computers running Garuda Linux.

**Comment by Technetium1** [comment]
@stefanwimmer128 is that really the only way?
https://bugs.gentoo.org/802285#c1
https://bugs.archlinux.org/task/63075

**Comment by stefanwimmer128** [comment]
@Technetium1 Not sure, ultimately it's up to the maintainer to decide whether it's safe to remove the extension signing requirement.
I'm just offering to maintain my own fork - which I'm already doing to make manually building it easier ([AUR](https://aur.archlinux.org/packages/firedragon-unsigned-extensions), [CI-Builds](https://git.stefanwimmer128.eu/stefanwimmer128/firedragon-unsigned-extensions/-/packages)) -, in case it is not feasible to change it for all users.

**Comment by Technetium1** [comment]
Looks like the flag can be altered such that you can install unsigned extensions into the install dir though?

**Comment by stefanwimmer128** [comment]
Firedragon already includes the flag [`--with-unsigned-addon-scopes=app,system`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=firedragon#n118) and it does work, but it only allows installing unsigned extensions by manually putting them in `/usr/lib64/firefox/browser/extensions`, what I need is to able to install them for a single profile in `about:addons` using the `Install Add-on From File...`-Option. For that I only found the solution provided by dr460nf1r3.

But I realize this is a very specific use case, which is why I really wouldn't mind maintaining my own fork.

**Comment by dr460nf1r3** [comment]
Sounds good to me!

**Comment by dr460nf1r3** [comment]
Eh I noticed you actually did it. Nice to see! :)

**Comment by SFort** [comment]
Could we please get this in the main package,
it feels very silly having to spend way more time compiling a separate build of a browser, specificly for installing a thrown together addon.

**Comment by stefanwimmer128** [comment]
Compiling is not necessary since the package is either available prebuilt as [firedragon-unsigned-extensions-bin](https://aur.archlinux.org/packages/firedragon-unsigned-extensions-bin) or in my own [repository](https://git.stefanwimmer128.xyz/stefanwimmer128/arch-repo) or can be manually downloaded from my [GitLab](https://git.stefanwimmer128.xyz/stefanwimmer128/firedragon-unsigned-extensions/-/packages).

**Comment by SFort** [comment]
Still, extensions are a basic function, they shouldn't need a special version of a browser.
although thanks for pointing out there's a -bin package, i do need it

**Comment by stefanwimmer128** [comment]
Latest versions now allow installation of unsigned extensions by default.

**Comment by dr460nf1r3** [comment]
Yes indeed, thanks for taking care!
