### ISSUE TITLE
canvas broken text

### ISSUE THREAD

**Issue by erxson** [dr460nf1r3/firedragon-browser#58]
![изображение](https://user-images.githubusercontent.com/50082485/225685191-48c5de25-38a6-4463-9482-30211d6e9ac8.png)
Fixed by disabling `privacy.resistFingerprinting.autoDeclineNoUserInputCanvasPrompts`, but click on prompt for every page is not cool.
Such thing on 110.0.1 version, latest Garuda Linux

**Comment by dr460nf1r3** [comment]
This is actually by design of the anti-fingerprinting feature, I don't consider it a bug. I rarely visit websites that need canvas access and when I do, its easy to enable by clicking the icon left to the URL bar. If it really annoys you a lot, disabling anti-fingerprinting is the way.

**Comment by ioc2e3** [comment]
> ... . If it really annoys you a lot, disabling anti-fingerprinting is the way.

That ...

I don't want to disable the fingerprint recognition function ...

Are there any other methods ?

.

**Comment by Technetium1** [comment]
There is not. If a site requires fingerprinting then you don't have much choice.
