### ISSUE TITLE
How to remove the pocket item from the right click menu?

### ISSUE THREAD

**Issue by fengwang** [dr460nf1r3/firedragon-browser#6]
[This page](https://help.getpocket.com/article/1025-disabling-save-to-pocket-features-in-firefox) gives a solution for Firefox, but does not work for Firedragon as there is no such a 'pocket' icon exist. Is there a way to disable  it?

**Comment by dr460nf1r3** [comment]
Pocket is disabled by default in `firedragon.cfg`, this doesn't seem to affect rightlick menus. I don't know how to remove it from there though :/

**Comment by Thorin-Oakenpants** [comment]
this hides (if not already removed) the icon from the toolbar and all context menus
```
user_pref("extensions.pocket.enabled", false); // Pocket Account [FF46+]
```

**Comment by dr460nf1r3** [comment]
This is in fact already present in `firedragon.cfg`, it just doesn't hide context menus :)

**Comment by Thorin-Oakenpants** [comment]
It works in Firefox, I use it (windows). If it's not working in yours, then it's either an OS dependent bug, or you ripped out/stopped the code that uses it

see https://searchfox.org/mozilla-central/search?q=extensions.pocket.enabled&path=&case=false&regexp=false

e.g. `hasPocket`
- https://searchfox.org/mozilla-central/source/browser/base/content/test/contextMenu/browser_contextmenu_input.js#231
- https://searchfox.org/mozilla-central/source/browser/base/content/test/contextMenu/browser_contextmenu.js#100

**Comment by dr460nf1r3** [comment]
It turned out a Librewolf patch was blocking this. It has been removed and now things work as expected (no more right click entry)
