### ISSUE TITLE
Cant Sync addons

### ISSUE THREAD

**Issue by SmurgBurglar** [dr460nf1r3/firedragon-browser#65]
I have logged into my firefox account and disabled "disable firefox accounts" but my extensions wont sync.

**Comment by dr460nf1r3** [comment]
Hey :) If you are trying to use Mozillas sync server, then this is expected. We use our own. You can however override this via the overrides file mentioned in the readme.

**Comment by dr460nf1r3** [comment]
The correct value for the tokenserver value is: 
```
lockPref("identity.sync.tokenserver.uri", "https://token.services.mozilla.com/1.0/sync/1.5");
```

**Comment by SmurgBurglar** [comment]
still nothing my overrides.cfg look's like this
 "DisableFirefoxAccounts": false,

defaultPref("privacy.userContext.enabled", true); // this breaks loggin into FF syncserver

lockPref("identity.sync.tokenserver.uri", "https://token.services.mozilla.com/1.0/sync/1.5");

**Comment by dr460nf1r3** [comment]
If you go to `about:config`, does it show the right URL? Also, try relogging if you didn't do that already please.

**Comment by dr460nf1r3** [comment]
Closing due to the lack of answer.
