### ISSUE TITLE
Additional patches needed to compile with Rust 1.73

### ISSUE THREAD

**Issue by stefanwimmer128** [dr460nf1r3/firedragon-browser#69]
Rust 1.73 recently landed and this completely breaks compiling firefox.

Thus additional patches, provided by gentoo, are needed: 0027-bgo-915306-rust-1.73-compatibility-patch1.patch, 0027-bgo-915306-rust-1.73-compatibility-patch2.patch (https://dev.gentoo.org/~juippis/mozilla/patchsets/firefox-118-patches-04.tar.xz)

**Comment by dr460nf1r3** [comment]
This probably concerns the Arch side, right?

**Comment by stefanwimmer128** [comment]
Yes, since Arch updated to Rust 1.73 these patches are required to build firefox.

**Comment by dr460nf1r3** [comment]
Thanks for letting us know! ☺️

@FGD-Garuda the next one will need this added to the PKGBUILD 😸

**Comment by dr460nf1r3** [comment]
Updated in https://aur.archlinux.org/cgit/aur.git/commit/?h=firedragon&id=dea75d3817a8ee409c97f47e717943c29eea1c47, thanks!
