### ISSUE TITLE
Address bar context menu theming

### ISSUE THREAD

**Issue by l4kr** [dr460nf1r3/firedragon-browser#7]
Hi! 

When I right-click the search bar, the context menu is white, which looks ugly compared to the rest of the browser.

Is this fixable?
(sorry for the picture, can't screenshot the context menu with my screenshot app)

![IMG_1176](https://user-images.githubusercontent.com/73653844/144712291-447e76dd-2a18-496d-9f95-ceba2eeaf5ca.JPG)

**Comment by dr460nf1r3** [comment]
This is most likely related to the Sweet theme needing an update, a fitting issue has been opened already here https://github.com/EliverLara/firefox-sweet-theme/issues/70 :)
