### ISSUE TITLE
Can't download files

### ISSUE THREAD

**Issue by SmurgBurglar** [dr460nf1r3/firedragon-browser#70]
Attempting to download files does nothing and deactivating all add-ons and entering troubleshooting mode has not helped.

**Comment by dr460nf1r3** [comment]
Have an example download link?

**Comment by SmurgBurglar** [comment]
it's everything if i right click and choose save as on the silhouetted cat icon on the top left hand corner of the page nothing happens same if i click on a download link.

**Comment by SmurgBurglar** [comment]
It's working again now, don't know why.

**Comment by dr460nf1r3** [comment]
Glad to hear its no longer an issue.
