### ISSUE TITLE
firedragon or firedragon-next ?

### ISSUE THREAD

**Issue by thealio** [dr460nf1r3/firedragon-browser#72]
Hi,
I've notice that `firedragon` is still to version 119.0 , while `librewolf` is to version 121.
There's also `firedragon-next`, based on `floorp`

At this point, it's not clear to me if `firedragon` package is still maintained , and if the project has moved to `firedragon-next `, and there is no in formations on the github page

**Comment by dr460nf1r3** [comment]
Hi! We are currently in progress of rebasing to Floorp, which is also why our main focus are getting the new builds up. You can read more about the process over [here](https://forum.garudalinux.org/t/new-firedragon-version/33729) :)

**Comment by thealio** [comment]
Thank you!
Since I really like the propose of Floorp browser as well as ESR Firefox , I'll move to `firedragon-next`

A general advise for this rebrand: if this isn't already done , remove pocket from the build (or replace it with an open-source alternative)
Cheers

**Comment by thealio** [comment]
> firedragon-next

Has `firedragon-next` been removed from chaotic-aur?
Currently, it's not present anymore

**Comment by dr460nf1r3** [comment]
Yes, it was a test build and current ones can be obtained via the method linked in the forum thread 👀

**Comment by andika207** [comment]
> Hi! We are currently in progress of rebasing to Floorp

@K4sum1 @Alex313031

**Comment by K4sum1** [comment]
Not sure why you mentioned me in a browser I've never heard of but ok.

**Comment by Alex313031** [comment]
@andika207 Are you saying I should add some patches from here into Mercury?

**Comment by andika207** [comment]
@Alex313031 I think Floorp doesn't support CPU's without SSE4 instructions and many people hype it up 
https://www.reddit.com/r/browsers/comments/194h967/opinion_just_use_whatever_you_feel_comfortable/

**Comment by dr460nf1r3** [comment]
Since the new version has been officially released, this issue may be closed.
