### ISSUE TITLE
Vimium extension broken since change to Floorp

### ISSUE THREAD

**Issue by Norgus** [dr460nf1r3/firedragon-browser#73]
Expected behaviour: keyboard shortcuts for page navigation, tab manipulation, and so on function when their assigned keys are pressed
Symptoms: Not a single shortcut I have tried works, including the one to display the extension's help.

The vimium extension does not appear to be functional (at all, as far as I can tell)
URL is https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/

I tried removing and adding it fresh, ensuring it is given the permissions it needs, and did a browser restart and page refresh to be sure.
It worked on the librewolf base.

**Comment by Technetium1** [comment]
@dr460nf1r3 I went to blindly investigate a bit before testing and found this mysterious thing, with [a dead link to reference](https://github.com/dr460nf1r3/firedragon-browser/blob/ef68ef7903a0089f6a15638f8c4cba0a98ad361f/firedragon.cfg#L400). Here's the [archived version](https://archive.is/GCPAn).
https://github.com/dr460nf1r3/firedragon-browser/blob/ef68ef7903a0089f6a15638f8c4cba0a98ad361f/firedragon.cfg#L404
What am I missing, I don't see where `5` would be a valid setting?

---

I suspected CSP could be problematic, but it [it's not actually being altered](https://github.com/dr460nf1r3/firedragon-browser/blob/master/firedragon.cfg#L425-L426). CSP issue as reference: 
```c
github.com/philc/vimium/issues/2926
```

Then came actual testing and gave it permissions, and it "just worked", so I can't even reproduce the problem in the first place!

@Norgus when you say given the permissions it needs, you mean this box, correct? When I check it, the extension seems to work.
![image](https://github.com/dr460nf1r3/firedragon-browser/assets/9877150/0a80d859-7fe4-460e-86a5-25e14d0655b8)

**Comment by Norgus** [comment]
@Technetium1 Thanks for testing! I did indeed mean that permission toggle, and I've gone and double-checked it, so did another reinstall of the extension and toggled it fresh, but I'm still not getting a response on any of the key bindings from vimium.

I'll try a few things (disable other extensions, maybe try a fresh profile)

**Comment by Norgus** [comment]
Okay, so disabling all other extensions didn't help, but switching away from my old migrated profile to use the 'default' profile did.
Maybe there's a problem with the profile migration between librewolf and florp?
The profile switch fixed my other essential broken extension (keepass xc), too.

Should I close the two extension-specific issues and raise some kind of 'potential migration issue with extensions' issue?

**Comment by Technetium1** [comment]
@Norgus a new profile is definitely required. There should have been a notice about it when pacman updated it 👀 
https://forum.garudalinux.org/t/new-firedragon-major-version/34585?u=technetium

**Comment by Norgus** [comment]
I think I misunderstood this part to mean that what could be migrated would be and the fresh profile would be sorted out in the install.

`garuda-update will carry out the needed actions automatically while updating`

I'll close the issue.
