### ISSUE TITLE
Couldn't load XPCOM

### ISSUE THREAD

**Issue by Arndorferd** [dr460nf1r3/firedragon-browser#76]
Newest update causes 

XPCOMGlueLoad error for file /usr/lib/firedragon/libxul.so:
libvpx.so.9: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

when trying to open firedragon in 6.7.0-0-MANJARO

**Comment by Technetium1** [comment]
Cannot reproduce; but not using Manjaro. What is your output for this? Please confirm you're up to date too.
```
[tech@lynx ~]$ sudo pacman -Fy libvpx.so
:: Synchronizing package databases...
extra/libvpx 1.14.0-1 [installed]
    usr/lib/libvpx.so
multilib/lib32-libvpx 1.14.0-1
    usr/lib32/libvpx.so
```

**Comment by dr460nf1r3** [comment]
Self-built from AUR?

**Comment by Arndorferd** [comment]
> Cannot reproduce; but not using Manjaro. What is your output for this? Please confirm you're up to date too.
> 
> ```
> [tech@lynx ~]$ sudo pacman -Fy libvpx.so
> :: Synchronizing package databases...
> extra/libvpx 1.14.0-1 [installed]
>     usr/lib/libvpx.so
> multilib/lib32-libvpx 1.14.0-1
>     usr/lib32/libvpx.so
> ```

Mine is

:: Synchronizing package databases...
 core
 extra
 community
 multilib
 chaotic-aur
extra/libvpx 1.13.1-1 [installed]
    usr/lib/libvpx.so
multilib/lib32-libvpx 1.13.1-1 [installed]
    usr/lib32/libvpx.so

**Comment by dr460nf1r3** [comment]
> chaotic-aur

Using Chaotic-AUR with Manjaro makes such errors expected as package versions may lag behind. I suggest building it yourself from AUR to work around that.

**Comment by Arndorferd** [comment]
Lol no, the version is behind in the AUR itself, Chaotic aur just gives options, I dont need to use it.

**Comment by Arndorferd** [comment]
![Screenshot_20240214_074327](https://github.com/dr460nf1r3/firedragon-browser/assets/41760727/a6d03d1d-3830-48c2-918c-30feeaf4b948)

**Comment by dr460nf1r3** [comment]
So *is* the firedragon package self-built or is it the one from CAUR?

**Comment by Arndorferd** [comment]
> So _is_ the firedragon package self-built or is it the one from CAUR? In any case sourcing from there makes such errors expected as we build against Arch lib versions.

I dont believe it matters, I think its because libvpx is out of date in the AUR. Im getting this only after an update of firedragon.

**Comment by Arndorferd** [comment]
Manjaro is often slow in updating its packages

**Comment by dr460nf1r3** [comment]
> > So _is_ the firedragon package self-built or is it the one from CAUR? In any case sourcing from there makes such errors expected as we build against Arch lib versions.
> 
> I dont believe it matters, I think its because libvpx is out of date in the AUR. Im getting this only after an update of firedragon.

I don't think I understand. What does the AUR package have to do with it? Libvpx should be a package provided by Manjaro which, as you noted yourself, is slower with updating packages.

**Comment by Technetium1** [comment]
> I think its because libvpx is out of date in the AUR

This is not the case, as [it is actually provided in **Arch's `extra` repo**](https://archlinux.org/packages/extra/x86_64/libvpx/). For this reason, you can blame Manjaro, and you _will_ continue to have issues when not building it yourself in the context of correct dependencies.


> Manjaro is often slow in updating its packages

Yes; exactly 😞… The issue you have is that Manjaro doesn't push the new version to their mirrors, so it will fail until then. Your best bet is going to be [opening a Manjaro forum post](https://docs.manjaro.org/effectively-using-the-forum-to-get-support/) and requesting that the package gets bumped.

**Comment by Arndorferd** [comment]
Is there a reason though the package requirements for this are so bleeding edge though. Manjaro is a bit annoying in that regard and it has happened with other things but I think its happened several times for just firedragon and not other similar programs like firefox.

**Comment by Arndorferd** [comment]
Also I saw 

> > 
> 
> This is not the case, as [it is actually provided in **Arch's `extra` repo**](https://archlinux.org/packages/extra/x86_64/libvpx/). For this reason, you can blame Manjaro, and you _will_ continue to have issues when not building it yourself in the context of correct dependencies.

but it has no git clone even and I have extra in my repository list as you saw here

core
extra
community
multilib
chaotic-aur
extra/libvpx 1.13.1-1 [installed]
usr/lib/libvpx.so
multilib/lib32-libvpx 1.13.1-1 [installed]
usr/lib32/libvpx.so

so I wasnt sure if that package was even in a ready to use state?

**Comment by Arndorferd** [comment]
Ok so I guess these extra repositories can be installed using pacman -U after downloading their respective zips directly which I didnt realize and they do work. It was kinda a dependency hell but I did update things manually. My question remains though why does firedragon have such bleeding edge requirements?

**Comment by dr460nf1r3** [comment]
I would be careful about simply upgrading like that. It might break every other package depending on that package..

It does not need bleeding edge deps, it's simply built against those libs. Have version x while compiling? You now need it at runtime too. It's y? Well sure but now you need y and can't run it with x.

**Comment by Technetium1** [comment]
@Arndorferd as just mentioned, you will possibly break some things as a consequence, so you should look at the `Required By` column [for libvpx](https://archlinux.org/packages/extra/x86_64/libvpx/) to see what can be affected. I personally tend to share a lot of similar grievances towards Manjaro for same issue you're currently experiencing: https://github.com/arindas/manjarno

**Comment by Arndorferd** [comment]
I understand the risks but it was only ffmpeg and its dependancies that stood in the way and I updated what was required without flags. Ill take it as it comes but I dont think anything I need will be of issue.
