### ISSUE TITLE
Firedragon update caused metamask to break

### ISSUE THREAD

**Issue by Arndorferd** [dr460nf1r3/firedragon-browser#79]
The last update that switched to floorp based browser, causes metamask to spin pinwheel endlessly and not function.

**Comment by dr460nf1r3** [comment]
Is this a website or browser plugin? Would you be so kind to confirm whether it works on plain Floorp?

**Comment by Arndorferd** [comment]
It was because I had spoof user agent on

**Comment by dr460nf1r3** [comment]
So am I understanding right this is solved by turning it off?
