### ISSUE TITLE
AppImage not launching on Linux

### ISSUE THREAD

**Issue by Neigdoig** [dr460nf1r3/firedragon-browser#81]
I tried downloading your AppImage and running it on Linux Mint 21.3, and I get an error related to libappimage, saying that it isn't "registered", whatever that means. Maybe you can take a look at that?

**Comment by stefanwimmer128** [comment]
Does this still happen with the [latest releases](https://gitlab.com/garuda-linux/firedragon/builder/-/releases)?

**Comment by Neigdoig** [comment]
After getting that release, it works. Maybe an upgrade to Mint 22 and a new release did the trick.

**Comment by dr460nf1r3** [comment]
More likely that we build AppImages in an "official" way. The previous one was more or less just a NixOS package with direct launch capabilities.

**Comment by Neigdoig** [comment]
So potentially, when I originally got your browser, it was built with Nix in mind?

**Comment by dr460nf1r3** [comment]
No, in fact it was PKGBUILD only for a long time. Then NixOS came and since it was easy to build an AppImage like thing with the existing package, this is the way it played out. Now there is a proper binary tarball to build the AppImages from, which is much better.
