### ISSUE TITLE
How to download?

### ISSUE THREAD

**Issue by slrgt** [dr460nf1r3/firedragon-browser#83]
Theres no releases, no link to the gitlab, the gitlab doesnt have releases, there's no installation isntructions. Project looks great but very difficult for people to try. Is there a flatpak or rpm package?

**Comment by dr460nf1r3** [comment]
Hi! We currently offer builds for Archlinux and NixOS, pre-built via [Chaotic-AUR](https://aur.chaotic.cx) or [Chaotic Nyx](https://nyx.chaotic.cx). There are ongoing works for a build system, which might bring it to other distributions in the future.

**Comment by slrgt** [comment]
Is a flatpak in the plans?

**Comment by dr460nf1r3** [comment]
It should be feasible, yes! No ETA though.

**Comment by stefanwimmer128** [comment]
Now available either as [Flatpak](https://flathub.org/apps/org.garudalinux.firedragon) or [AppImage](https://gitlab.com/garuda-linux/firedragon/builder/-/releases).

**Comment by FGD-Garuda** [comment]
> Hope there is a FireDragon Browser for Windows ...

Version 12 has one, in the [artifacts](https://gitlab.com/garuda-linux/firedragon/firedragon12/-/commit/2f4de2ebe794046b0bb95fe3d3a21537f1c8b688/pipelines) on the right side of the page, there is a long list of 24 artifacts.
Keep in mind this is still a beta version and not official build yet.
