### ISSUE TITLE
it doesnt start on my manjaro steam deck

### ISSUE THREAD

**Issue by Janter1603** [dr460nf1r3/firedragon-browser#92]
click it, loads, stops loading,
no browser
only sadness

**Comment by dr460nf1r3** [comment]
I can imagine that you are using Chaotic-AUR to get it? There might be library mismatches in that case leading to non-opening apps.

**Comment by Technetium1** [comment]
May possibly be fixed by https://github.com/flathub/org.garudalinux.firedragon/commit/529a6a32d2f9b59db14132dc298beb212de6bda0 if it was the flatpak

**Comment by dr460nf1r3** [comment]
Feel free to comment if the issue persists.
