### ISSUE TITLE
gmx.com stoppped functioning normally

### ISSUE THREAD

**Issue by Ryder17z** [dr460nf1r3/firedragon-browser#96]
![image](https://github.com/user-attachments/assets/df341bea-36bf-410a-89ca-04acec2c904f)

the "limited functionality" mode only makes sense on a phone or tablet. it doesn't size itself for use on PC. on a 4k screen you get a very small "viewport" instead of normal behavior.

it seems the Useragent string function is not only depricated, but actually broken right now as the website does not recognize changes to it.

**Comment by Technetium1** [comment]
This may be a site issue as it currently won't load for me even in Google Chrome: `An error has occurred. Please reload the page.`

**Comment by calendulish** [comment]
the build you are using probably don't have an updated firedragon.cfg. what you can do is close your browser and create the file ~/.firedragon/firedragon.overrides.cfg with the content

```
defaultPref("general.useragent.override", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36");
```

it will fix, until you have a new build
