### ISSUE TITLE
I can't download anything?

### ISSUE THREAD

**Issue by BinaryHarbinger** [dr460nf1r3/firedragon-browser#98]
I tried to change privacy and other download settings but I'm not able to install anything.

**Comment by BinaryHarbinger** [comment]
> I tried to change privacy and other download settings but I'm not able to install anything.

I'm able to install stuf with Floorp tough

**Comment by dr460nf1r3** [comment]
Could you specify what exactly you are trying to download, and what "failing" looks like?

**Comment by BinaryHarbinger** [comment]
> Could you specify what exactly you are trying to download, and what "failing" looks like?

sorry but it looks like nothing. ı changed settings to warn everytime. Warning appears and lets me choose what to do (openning the file or just keeping it) but when I click "ok" button my download disappears. There is nothing in my download history. I'm using browser with all the privacy settings enabled.

**Comment by comradeferret** [comment]
I'm getting this too.  Here is the problem, but I don't know the fix.  It's specifically in Wayland environments, I think, without native Xwayland support (ie sway, niri).

Server is missing xdg_foreign support [Parent 29711, Main Thread] WARNING: Failed to export handle, could not set transient for: 'glib warning', file /home/main-builder/pkgwork/src/firedragon-v11.18.1-1/toolkit/xre/nsSigHandlers.cpp:187

**Comment by stefanwimmer128** [comment]
@comradeferret Sway & niri should support xdg_foreign (https://wayland.app/protocols/xdg-foreign-unstable-v2#compositor-support). Can you check that your using the latest version?

**Comment by stefanwimmer128** [comment]
I think this might be a `xdg-desktop-portal` issue. Could you try setting the following in [firedragon.overrides.cfg](https://gitlab.com/stefanwimmer128/firedragon-settings/-/blob/master/firedragon.overrides.cfg?ref_type=heads):

```
lockPref("widget.use-xdg-desktop-portal.file-picker", 0);
```

**Comment by stefanwimmer128** [comment]
Alternatively you could try installing `xdg-desktop-portal-gtk` and configure it to be used as file chooser portal: `~/.config/xdg-desktop-portal/portals.conf`

``` toml
[preferred]
default=wlr
org.freedesktop.impl.portal.FileChooser=gtk
```

**Comment by comradeferret** [comment]
The xdg-desktop-portal solution fixed it for me.  I still get the error in console, but I'm able to download things.  Thank you!
